1. Create a NumPy array of integers from 1 to 10.

In [8]:
import numpy as np

In [ ]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

2. Create a 2x3 NumPy array filled with zeros.


In [ ]:
arr=np.zeros((2,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

3. Create a NumPy array of even numbers from 2 to 20

In [ ]:
arr=np.arange(2,22,2)
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

4. Given two NumPy arrays, arr1 = np.array([1, 2, 3]) and arr2 = np.array([4,
5, 6]), perform element-wise addition, subtraction, multiplication, and
division between the two arrays.


In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

In [ ]:
#addition
arr3=arr1+arr2
arr3

array([5, 7, 9])

In [ ]:
#subtraction
arr4=arr1-arr2
arr4

array([-3, -3, -3])

In [ ]:
#multiplication
arr5=arr1*arr2
arr5

array([ 4, 10, 18])

In [ ]:
#division
arr6=arr1/arr2
arr6

array([0.25, 0.4 , 0.5 ])

5. Compute the mean, median, and standard deviation of a NumPy array
containing 100 random numbers.


In [9]:
arr=np.random.rand(100)
arr

array([0.03108811, 0.34344101, 0.62559202, 0.50994317, 0.92902855,
       0.82133479, 0.05036571, 0.17615519, 0.36041828, 0.59129254,
       0.08790594, 0.62469979, 0.97772791, 0.19164881, 0.5559608 ,
       0.85166014, 0.7749245 , 0.40322528, 0.66217763, 0.51438871,
       0.09628029, 0.02343831, 0.23197017, 0.45835979, 0.86399649,
       0.73031474, 0.46772489, 0.38007998, 0.55361629, 0.67286755,
       0.0319089 , 0.65911926, 0.71098758, 0.66573428, 0.95153269,
       0.80167809, 0.1440585 , 0.99964576, 0.73274937, 0.38924256,
       0.42100184, 0.32580849, 0.24303581, 0.54638175, 0.58335966,
       0.31909562, 0.46294558, 0.52069179, 0.09621716, 0.14352881,
       0.8564521 , 0.36969724, 0.7767245 , 0.06483357, 0.82800534,
       0.03541694, 0.46882584, 0.99134895, 0.90372914, 0.05822316,
       0.14791572, 0.58623995, 0.01802678, 0.36393965, 0.99154125,
       0.00129497, 0.78375145, 0.6693777 , 0.75736472, 0.36084542,
       0.11136166, 0.81528697, 0.15306405, 0.37744264, 0.27913

In [10]:
arr.mean()

0.49070219523356345

6. Reshape a 1D NumPy array of 12 random elements into a 2D array with a
shape of (3, 4)

In [15]:
arr=np.random.randint(0,20,12)
arr

array([ 6, 16,  7, 16,  8,  5,  5,  5,  9, 14,  8, 10])

In [16]:
arr.reshape(3,4)

array([[ 6, 16,  7, 16],
       [ 8,  5,  5,  5],
       [ 9, 14,  8, 10]])

7. Given a NumPy array arr = np.array([1, 2, 3, 4, 5]), square each element in
the array using NumPy functions.

In [17]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [18]:
np.square(arr)

array([ 1,  4,  9, 16, 25])

8. Create a 5x5 identity matrix using NumPy.

In [20]:
arr=np.eye(5,5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

9. Calculate the dot product of two NumPy arrays, a = np.array([1, 2, 3]) and
b = np.array([4, 5, 6]).

In [23]:
a=np.array([1,2,3])


In [24]:
b=np.array([4,5,6])

In [25]:
a.dot(b)

32

10.Find the index of the maximum value and the index of the minimum value
in a NumPy array.


In [26]:
a=np.array([4,5,6,7])
a

array([4, 5, 6, 7])

In [27]:
a.argmax()

3

In [28]:
a.argmin()

0

11.Concatenate two random NumPy arrays horizontally and vertically.

In [30]:
a=np.zeros((4,4))
b=np.ones((4,4))
c=np.concatenate((a,b))
d=np.concatenate((a,b),axis=1)
print("vertical concatenate-\n",c)
print("horizontal concatenate-\n",d)

vertical concatenate-
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
horizontal concatenate-
 [[0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1.]]


12.Given a 2D NumPy array, calculate the sum of each row and each column
separately.

In [38]:
arr=np.arange(1,17).reshape(4,4)
print(arr)
print("sum of each column is",np.sum(arr,axis=0))
print("sum of each row is",np.sum(arr,axis=1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
sum of each column is [28 32 36 40]
sum of each row is [10 26 42 58]


13.Find the common elements between two NumPy arrays

In [41]:
a=np.array([[3,2],[5,6],[1,7]])
b=np.array([[3,1],[5,4],[0,8]])
c=np.intersect1d(a,b)
print("The common element between a and b are",c)

The common element between a and b are [1 3 5]


14.Replace all negative values in a NumPy array with zeros.

In [42]:
a=np.array([1,2,3,-4,-5])
a[a<0]=0
a

array([1, 2, 3, 0, 0])

15.Create a NumPy array with random integers between 1 and 100 and then
sort it in ascending order.


In [43]:
arr=np.random.randint(0,101,100)
arr.sort()
arr

array([  1,   1,   4,   5,   5,   6,   6,   9,   9,  11,  13,  13,  13,
        13,  13,  13,  15,  15,  15,  15,  15,  16,  17,  20,  20,  23,
        24,  25,  25,  26,  28,  30,  32,  32,  34,  35,  37,  37,  38,
        39,  41,  41,  42,  47,  48,  49,  51,  51,  52,  54,  55,  57,
        58,  58,  58,  64,  65,  65,  65,  66,  66,  67,  68,  68,  68,
        71,  72,  73,  74,  75,  75,  76,  77,  78,  78,  80,  81,  81,
        82,  82,  82,  83,  83,  83,  84,  85,  87,  89,  90,  93,  93,
        94,  95,  95,  96,  99,  99,  99, 100, 100])

16.Calculate the element-wise absolute difference between two NumPy
arrays.

In [44]:
a=np.array([1,2,3,4])
b=np.array([2,4,6,8])
c=np.absolute(a-b)
print(c)

[1 2 3 4]


17.Given a 2D NumPy array, extract the first row and the last column.


In [45]:
arr=np.array([[1,2,4],[3,5,6],[7,8,9]])
firstrow=arr[0]
lastcol=arr[:,[-1]]
print("first row is\n",firstrow)
print("late colum is\n",lastcol)

first row is
 [1 2 4]
late colum is
 [[4]
 [6]
 [9]]


18.Slice a 1D NumPy array to get every other element.

In [46]:
a=np.array([1,2,3,4])
x=a[0:len(a)+1]
print(x)

[1 2 3 4]


19.Given a 2D NumPy array, extract a subarray consisting of the central 2x2
elements.


In [54]:
arr=np.array([[11,12,13,14,15,16],[21,22,23,24,25,26],[31,32,33,34,35,36],[41,42,43,44,45,46],[51,52,53,54,55,56]])
a=arr[2:4,[2,3]]
print("array\n",arr)
print("2x2 array\n",a)

array
 [[11 12 13 14 15 16]
 [21 22 23 24 25 26]
 [31 32 33 34 35 36]
 [41 42 43 44 45 46]
 [51 52 53 54 55 56]]
2x2 array
 [[33 34]
 [43 44]]


20.Reverse a 1D NumPy array using slicing.

In [55]:
a=np.array([1,2,3,4])
x=a[::-1]
x

array([4, 3, 2, 1])